# Generated by Django 4.2.2 on 2023-08-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='createdBy',
            new_name='created_by',
        ),
    ]
